spring.profiles.active: development
---
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:52.79.178.91}
    port: ${SPRING_NEO4J_PORT:7474}
    password: ${SPRING_NEO4J_PASSWORD:handler1}
    username: ${SPRING_NEO4J_USERNAME:neo4j}
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.99.101}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:52.79.178.91}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:52.79.178.91}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false
