server:
  port: ${PORT:8989}


turbine:
  appConfig: catalog-service,account-service,edge-service,inventory-service,order-service,user-service
  clusterNameExpression: 'default'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

---
spring:
  profiles: cloud
management:
  port: -1
